name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Adjust to match the name of your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    - name: Build Docker image
      run: docker build -t registry.heroku.com/dockerapp-final/web .

    - name: Push Docker image to Heroku
      run: docker push registry.heroku.com/dockerapp-final/web

    - name: Release the image on Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:release web -a dockerapp-final
        heroku logs --tail -a dockerapp-final
